export const OH_FIXED = 544323

export const RC = [
  { role: 'Senior Consultant - PO',   dept: 'Product Owner',    monthly: 60000, daily: 2727 },
  { role: 'Consultant - PO',          dept: 'Product Owner',    monthly: 50000, daily: 2273 },
  { role: 'Associate Consultant - PO',dept: 'Product Owner',    monthly: 40000, daily: 1818 },
  { role: 'Senior Specialist - PO',   dept: 'Product Owner',    monthly: 28000, daily: 1273 },
  { role: 'Specialist - PO',          dept: 'Product Owner',    monthly: 21000, daily: 955  },
  { role: 'Senior Analyst - PO',      dept: 'Product Owner',    monthly: 16000, daily: 727  },
  { role: 'Junior Analyst - PO',      dept: 'Product Owner',    monthly: 12000, daily: 545  },
  { role: 'Intern - PO',              dept: 'Product Owner',    monthly: 3000,  daily: 136  },
  { role: 'Senior Consultant - PM',   dept: 'Project Manager',  monthly: 50000, daily: 2273 },
  { role: 'Consultant - PM',          dept: 'Project Manager',  monthly: 42000, daily: 1909 },
  { role: 'Associate Consultant - PM',dept: 'Project Manager',  monthly: 35000, daily: 1591 },
  { role: 'Senior Specialist - PM',   dept: 'Project Manager',  monthly: 26000, daily: 1182 },
  { role: 'Specialist - PM',          dept: 'Project Manager',  monthly: 20000, daily: 909  },
  { role: 'Senior Analyst - PM',      dept: 'Project Manager',  monthly: 16200, daily: 736  },
  { role: 'Junior Analyst - PM',      dept: 'Project Manager',  monthly: 10000, daily: 455  },
  { role: 'Intern - PM',              dept: 'Project Manager',  monthly: 3000,  daily: 136  },
  { role: 'Senior Consultant - BA',   dept: 'Business Analyst', monthly: 50000, daily: 2273 },
  { role: 'Consultant - BA',          dept: 'Business Analyst', monthly: 40000, daily: 1818 },
  { role: 'Associate Consultant - BA',dept: 'Business Analyst', monthly: 31000, daily: 1409 },
  { role: 'Senior Specialist - BA',   dept: 'Business Analyst', monthly: 24000, daily: 1091 },
  { role: 'Specialist - BA',          dept: 'Business Analyst', monthly: 18000, daily: 818  },
  { role: 'Senior Analyst - BA',      dept: 'Business Analyst', monthly: 15000, daily: 682  },
  { role: 'Junior Analyst - BA',      dept: 'Business Analyst', monthly: 11000, daily: 500  },
  { role: 'Intern - BA',              dept: 'Business Analyst', monthly: 3000,  daily: 136  },
  { role: 'Senior Consultant - UIUX', dept: 'UI/UX',            monthly: 13300, daily: 605  },
  { role: 'Consultant - UIUX',        dept: 'UI/UX',            monthly: 12540, daily: 570  },
  { role: 'Associate Consultant - UIUX', dept: 'UI/UX',         monthly: 11400, daily: 518  },
  { role: 'Senior Specialist - UIUX', dept: 'UI/UX',            monthly: 7220,  daily: 328  },
  { role: 'Specialist - UIUX',        dept: 'UI/UX',            monthly: 5700,  daily: 259  },
  { role: 'Senior Analyst - UIUX',    dept: 'UI/UX',            monthly: 4560,  daily: 207  },
  { role: 'Junior Analyst - UIUX',    dept: 'UI/UX',            monthly: 3420,  daily: 155  },
  { role: 'Intern - UIUX',            dept: 'UI/UX',            monthly: 456,   daily: 21   },
  { role: 'Senior Consultant - FE',   dept: 'Front End',        monthly: 13300, daily: 605  },
  { role: 'Consultant - FE',          dept: 'Front End',        monthly: 11020, daily: 501  },
  { role: 'Associate Consultant - FE',dept: 'Front End',        monthly: 9120,  daily: 415  },
  { role: 'Senior Specialist - FE',   dept: 'Front End',        monthly: 6840,  daily: 311  },
  { role: 'Specialist - FE',          dept: 'Front End',        monthly: 5700,  daily: 259  },
  { role: 'Senior Analyst - FE',      dept: 'Front End',        monthly: 4560,  daily: 207  },
  { role: 'Junior Analyst - FE',      dept: 'Front End',        monthly: 3800,  daily: 173  },
  { role: 'Intern - FE',              dept: 'Front End',        monthly: 456,   daily: 21   },
  { role: 'Senior Consultant - BE',   dept: 'Back End',         monthly: 13300, daily: 605  },
  { role: 'Consultant - BE',          dept: 'Back End',         monthly: 11020, daily: 501  },
  { role: 'Associate Consultant - BE',dept: 'Back End',         monthly: 9120,  daily: 415  },
  { role: 'Senior Specialist - BE',   dept: 'Back End',         monthly: 6840,  daily: 311  },
  { role: 'Specialist - BE',          dept: 'Back End',         monthly: 5700,  daily: 259  },
  { role: 'Senior Analyst - BE',      dept: 'Back End',         monthly: 4560,  daily: 207  },
  { role: 'Junior Analyst - BE',      dept: 'Back End',         monthly: 3800,  daily: 173  },
  { role: 'Intern - BE',              dept: 'Back End',         monthly: 456,   daily: 21   },
  { role: 'Senior Consultant - Mobile', dept: 'Mobile',         monthly: 13300, daily: 605  },
  { role: 'Consultant - Mobile',      dept: 'Mobile',           monthly: 11020, daily: 501  },
  { role: 'Associate Consultant - Mobile', dept: 'Mobile',      monthly: 9120,  daily: 415  },
  { role: 'Senior Specialist - Mobile', dept: 'Mobile',         monthly: 6840,  daily: 311  },
  { role: 'Specialist - Mobile',      dept: 'Mobile',           monthly: 5700,  daily: 259  },
  { role: 'Senior Analyst - Mobile',  dept: 'Mobile',           monthly: 4560,  daily: 207  },
  { role: 'Junior Analyst - Mobile',  dept: 'Mobile',           monthly: 3800,  daily: 173  },
  { role: 'Intern - Mobile',          dept: 'Mobile',           monthly: 456,   daily: 21   },
  { role: 'Senior Consultant - QA',   dept: 'Quality Assurance',monthly: 13300, daily: 605  },
  { role: 'Consultant - QA',          dept: 'Quality Assurance',monthly: 11020, daily: 501  },
  { role: 'Associate Consultant - QA',dept: 'Quality Assurance',monthly: 9120,  daily: 415  },
  { role: 'Senior Specialist - QA',   dept: 'Quality Assurance',monthly: 6840,  daily: 311  },
  { role: 'Specialist - QA',          dept: 'Quality Assurance',monthly: 5700,  daily: 259  },
  { role: 'Senior Analyst - QA',      dept: 'Quality Assurance',monthly: 4560,  daily: 207  },
  { role: 'Junior Analyst - QA',      dept: 'Quality Assurance',monthly: 3800,  daily: 173  },
  { role: 'Intern - QA',              dept: 'Quality Assurance',monthly: 456,   daily: 21   },
  { role: 'Senior Consultant - SM',   dept: 'Scrum Master',     monthly: 13300, daily: 605  },
  { role: 'Consultant - SM',          dept: 'Scrum Master',     monthly: 11020, daily: 501  },
  { role: 'Associate Consultant - SM',dept: 'Scrum Master',     monthly: 9120,  daily: 415  },
  { role: 'Senior Specialist - SM',   dept: 'Scrum Master',     monthly: 6840,  daily: 311  },
  { role: 'Specialist - SM',          dept: 'Scrum Master',     monthly: 5700,  daily: 259  },
  { role: 'Senior Analyst - SM',      dept: 'Scrum Master',     monthly: 4560,  daily: 207  },
  { role: 'Junior Analyst - SM',      dept: 'Scrum Master',     monthly: 3800,  daily: 173  },
  { role: 'Intern - SM',              dept: 'Scrum Master',     monthly: 456,   daily: 21   },
  { role: 'Web Designer',             dept: 'Design',           monthly: 13200, daily: 600  },
  { role: 'Validation Officer',       dept: 'Other',            monthly: 19000, daily: 864  },
]

export const PROP_STATUS = {
  draft:  { label: 'Draft',        color: 'tag-blue',   icon: '📝' },
  sent:   { label: 'Sent',         color: 'tag-purple', icon: '📤' },
  review: { label: 'Under Review', color: 'tag-gold',   icon: '🔍' },
  won:    { label: 'Won',          color: 'tag-green',  icon: '🏆' },
  lost:   { label: 'Lost',         color: 'tag-red',    icon: '❌' },
}

export const fmt = n => Math.round(n).toLocaleString('en-SA')

export const autoOHCat = (subtotal) => {
  if (subtotal <= 250000)  return '0.15'
  if (subtotal <= 1000000) return '0.20'
  if (subtotal <= 2000000) return '0.25'
  return '0.40'
}
